// This file will be auto-generated by Supabase CLI.
// Run: supabase gen types typescript --project-id <your-project-id> --schema public > src/types/supabase.ts
//
// Replace this comment and the Database interface below with the output of the command.
// You will need to install the Supabase CLI: https://supabase.com/docs/guides/cli

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      // Example table - replace with your actual tables
      users: {
        Row: {
          id: string
          created_at: string
          email: string | null
          name: string | null
          role: string | null // e.g., 'tenant', 'owner'
          phone_number: string | null
          profile_image_url: string | null
        }
        Insert: {
          id: string // Typically matches auth.users.id
          created_at?: string
          email?: string | null
          name?: string | null
          role?: string | null
          phone_number?: string | null
          profile_image_url?: string | null
        }
        Update: {
          id?: string
          created_at?: string
          email?: string | null
          name?: string | null
          role?: string | null
          phone_number?: string | null
          profile_image_url?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "users_id_fkey"
            columns: ["id"]
            referencedRelation: "users" // Supabase auth users table
            referencedColumns: ["id"]
          }
        ]
      }
      properties: {
        Row: {
            id: string
            created_at: string
            owner_id: string
            name: string
            address: string
            price: number
            description: string
            image_urls: string[] | null // Store as array of text in Supabase
        }
        Insert: {
            id?: string
            created_at?: string
            owner_id: string // Foreign key to users table
            name: string
            address: string
            price: number
            description: string
            image_urls?: string[] | null
        }
        Update: {
            id?: string
            created_at?: string
            owner_id?: string
            name?: string
            address?: string
            price?: number
            description?: string
            image_urls?: string[] | null
        }
        Relationships: [
          {
            foreignKeyName: "properties_owner_id_fkey"
            columns: ["owner_id"]
            referencedRelation: "users"
            referencedColumns: ["id"]
          }
        ]
      }
      // Add other tables like 'chat_conversations', 'chat_messages' as needed
    }
    Views: { [_ in never]: never }
    Functions: { [_ in never]: never }
    Enums: { [_ in never]: never }
    CompositeTypes: { [_ in never]: never }
  }
}

// Example type for user role, if you use an enum in Supabase or want stricter typing
export type UserRole = Database['public']['Tables']['users']['Row']['role']; // "tenant" | "owner" | null
